export const BOOK_LIST_REQUEST = 'BOOK_LIST_REQUEST'
export const BOOK_LIST_SUCCESS = 'BOOK_LIST_SUCCESS'
export const BOOK_LIST_FAIL = 'BOOK_LIST_FAIL'

export const BOOK_DETAILS_REQUEST = 'BOOK_DETAILS_REQUEST'
export const BOOK_DETAILS_SUCCESS = 'BOOK_DETAILS_SUCCESS'
export const BOOK_DETAILS_FAIL = 'BOOK_DETAILS_FAIL'

export const BOOK_CREATE_REVIEW_REQUEST = 'BOOK_CREATE_REVIEW_REQUEST'
export const BOOK_CREATE_REVIEW_SUCCESS = 'BOOK_CREATE_REVIEW_SUCCESS'
export const BOOK_CREATE_REVIEW_FAIL = 'BOOK_CREATE_REVIEW_FAIL'
export const BOOK_CREATE_REVIEW_RESET = 'BOOK_CREATE_REVIEW_RESET'

export const BOOK_RECOMMEND_REQUEST = 'BOOK_RECOMMEND_REQUEST'
export const BOOK_RECOMMEND_SUCCESS = 'BOOK_RECOMMEND_SUCCESS'
export const BOOK_RECOMMEND_FAIL = 'BOOK_RECOMMEND_FAIL'


export const BOOK_TOP_REQUEST='BOOK_TOP_REQUEST'
export const BOOK_TOP_SUCCESS='BOOK_TOP_SUCCESS'
export const BOOK_TOP_FAIL='BOOK_TOP_FAIL' 